name: "Continous Integration"

"on":
  pull_request:
    branches:
      - main

jobs:
  automation-test:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: https://forum-api.dicoding.dev/v1
    steps:
      - name: Checkout All Code
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm install
      - name: Create .env from .env.example
        run: cp .env.example .env && echo "VITE_API_URL=https://forum-api.dicoding.dev/v1" > .env
      - name: Run Unit Tests
        run: npm run ci:test
      - name: Run End to End Tests
        run: npm run e2e
